SELECT T.ANO,
       T.SEMESTRE,
       SUM(QTD_REPROVACAO) AS REPROVADOS,
       SUM(QTD_ALUNOS) AS TOTAL, 
       (SUM(QTD_REPROVACAO) / SUM(QTD_ALUNOS)) * 100 AS PORCETAGEM_REPROVADOS 
FROM FT_REPROVACAO R
JOIN DM_TEMPO T 
     ON R.ID_TEMPO = T.ID_TEMPO
WHERE EH_COTISTA = 1
GROUP BY T.ANO, T.SEMESTRE, EH_COTISTA
ORDER BY T.ANO, T.SEMESTRE;