SELECT T.ANO, T.SEMESTRE, DC.NM_CURSO, DD.NM_DEPARTAMENTO,
       SUM(QTD_REPROVACAO) AS REPROVADOS,
       SUM(QTD_ALUNOS) AS TOTAL,
       (SUM(QTD_REPROVACAO) / SUM(QTD_ALUNOS)) * 100 AS PORCETAGEM_REPROVADOS
FROM FT_REPROVACAO R
JOIN DM_TEMPO T ON R.ID_TEMPO = T.ID_TEMPO
JOIN DM_CURSO DC on R.ID_CURSO = DC.ID_CURSO
JOIN DM_DEPARTAMENTO DD on R.ID_DEPARTAMENTO = DD.ID_DEPARTAMENTO
GROUP BY T.ANO, T.SEMESTRE, DC.NM_CURSO, DD.NM_DEPARTAMENTO
ORDER BY T.ANO, T.SEMESTRE;