SELECT T.ANO, T.SEMESTRE, D.NM_DISCIPLINA,
       SUM(QTD_REPROVACAO) AS REPROVADOS,
       SUM(QTD_ALUNOS) AS TOTAL,
       (SUM(QTD_REPROVACAO) / SUM(QTD_ALUNOS)) * 100 AS PORCETAGEM_REPROVADOS
     FROM FT_REPROVACAO R
JOIN DM_TEMPO T ON R.ID_TEMPO = T.ID_TEMPO
JOIN DM_DISCIPLINA D ON R.ID_DISCIPLINA = D.ID_DISCIPLINA
GROUP BY T.ANO, T.SEMESTRE, D.NM_DISCIPLINA
ORDER BY T.ANO, T.SEMESTRE;

